import type { Metadata } from "next";
import '../globals.css';
import { ModalProvider } from '@/context/ModalContext'; // Import your ModalProvider

export const metadata: Metadata = {
  title: "QuickForms.io",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ModalProvider> {/* Wrap children with ModalProvider */}
          {children}
        </ModalProvider>
      </body>
    </html>
  );
}
